### CREATE CHANNEL

POST {{application}}/channel HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "link": "https://www.yahoo.com/news/rss/world",
  "categories": [
    "11eaa52d-eee9-bbd7-bc2c-0242ac1f0003"
  ]
}

> {%
    if(response.body["id"]) {
       client.global.set("channelId", response.body.id);
    }
%}

### GET CHANNEL

GET {{application}}/channel/11eaaa99-9adc-5338-993c-8f5f6ffe3894 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### GET CHANNELS

GET {{application}}/channel HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### DELETE CHANNEL

DELETE {{application}}/channel/{{channelId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
