server:
  port: 8081

spring:

  application.name: 'application'
  profiles.active: local

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
        format_sql: true
    open-in-view: false

  datasource:
    name: feeder-application-mysql
    url: jdbc:mysql://${datasource.host:localhost}:${datasource.port:3322}/${datasource.schema:application}
    username: feeder_application
    password: testpwd

  liquibase:
    contexts: ${spring.profiles.active}
    enabled: true

  devtools:
    livereload:
      enabled: false

  kafka:
    bootstrapServers: ${bootstrap.servers:localhost:9092}
    consumer:
      group-id: ${spring.application.name}
    producer:
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer

security:
  oauth2:
    resource:
      jwt:
        key-value: local_signing_key

feeder:
  kafka:
    enabled: true
  security:
    hierarchy.authorityPattern: >
      *:client-admin > *:client-delete > *:client-write > *:client-read
      *:admin > *:delete > *:write > *:read
  scheduling:
    task:
      update-channels:
        cron: 0 */15 * * * *
        batch-size: 10
    enabled: true

logging:
  level:
    org.feeder: DEBUG
    org.springframework: WARN
    org.hibernate: WARN
    liquibase: WARN
    org.apache.kafka: WARN
